import {storyPanel,landscapeBenefits} from './story-view.js';
import {FARM_PROJECT_TECH} from '../../src/game/model/economy.js';
import {FARM_PROJECT_NAMES} from '../../src/game/systems/agriculture.js';
import {courseArtUrl,artUrl,productArt} from './illustration.js';
import {INDUSTRY_PRODUCTS,SYSTEMS} from '../../src/game/model/industry.js';
import {productName} from '../../src/game/systems/industry-products.js';
import type {SessionObservation} from '../../src/runtime/session.js';
import {ERA_NODES,BRANCH_NODES,BRANCH_PATHS,BRANCH_PRODUCTS,COURSE_TRACKS} from '../../src/game/model/branches.js';
import {ALL_PRODUCTS,SUBJECT_NAMES} from '../../src/game/systems/economy-catalog.js';
import {esc,inputsText} from './economy-view.js';
import {treeGraph,type TreeNodeSpec} from './tree-view.js';
export const branchRequirements=(ids:string[]|undefined)=>ids?.map(id=>[...BRANCH_NODES,...ERA_NODES].find(n=>n.id===id)?.name??id).join(' + ')||'无';
const studyStages=[
 {name:'农场',era:'农耕村落',goal:'种好田，找到种子，守住收成',flow:'理论研习 → 实践点亮 → 田间生产 → 留种',notes:['开垦、普通灌溉与探索沿用田地行动；科技不替代种子和地块条件。','理论学习与播种分开；作物和设施需实践点亮，轮作、留种与探路效率等纯加成学完即生效。'],planned:['针对古树、巨石的清障工具升级尚未接入。']},
 {name:'工坊',era:'市镇百工',goal:'亲手做工具，把农产加工成产品',flow:'农产原料 → 工具制作 → 加工工序 → 动力升级',notes:['先学成形与连接，再分向磨粮、机械传动或泵；不必先学习工业用工。','公共磨坊随时代提供；自建工具与水力生产是可继续发展的支线。'],planned:['现可磨粮、榨油、加工亚麻纤维与绳索；织布和质量、损耗改进仍待接入。']},
 {name:'贸易',era:'电力工业',goal:'买设备入行，组织生产，再让产品售出',flow:'设备与用电 → 用工安排 → 持续采购与交付',notes:['基础招聘和手动买卖不需要先点科技；岗位资格、资金与设备条件仍需满足。','发电机和绕组制造归专业支线；用电基础不以发电机制造为前置。'],planned:['定价、宣传、销售渠道、库存与现金周转科技等待市场玩法接入，当前不可学习。']},
 {name:'资本',era:'现代社会',goal:'以资本配置为核心，具体玩法待定',flow:'资产 → 融资 → 投资 → 风险管理',notes:['既有农业、工坊和工业知识继续可用。配电与生产调度已归工业阶段。'],planned:['金融玩法尚未接入；暂不提供无实际效果的资本科技按钮。']},
];
export function branchPage(g:SessionObservation['game'],button:(id:string)=>string,selectedId='',selectedStage=-1,mode:'theory'|'practice'='theory'):string{
 const b=g.economy!.branchView!,current=g.era?.index??0;
 const stage=selectedStage>=0&&selectedStage<4?selectedStage:current,curriculum=studyStages[stage];
 const e=g.economy!,devices=e.industryView?.catalog.filter(p=>p.kind==='device'&&p.unlockStage===stage)??[];
 const equipment=`<details open class="school-equipment" id="school-equipment-${stage}"><summary>所用设备 <span>${devices.length} 项 · 已安装 ${devices.filter(p=>e.equipment[p.id]!==undefined).length} 项</span></summary><p>先学理论，再点亮相关实践；制作设备仍需材料与实际工期。</p><div class="school-equipment-grid">${devices.map(p=>{
  const spec=e.products.find(v=>v.id===p.id),durability=e.equipment[p.id];
  return `<article><img src="${artUrl(productArt(p.id))}" width="64" height="64" alt=""><div><h4>${esc(productName(p.id))}</h4><small>${durability===undefined?'未安装':durability<=0?'已安装 · 耐用耗尽':`已安装 · 耐用 ${durability}`}</small><p>${esc(spec?.effect??'')}</p><p>相关科技：${branchRequirements(p.knowledge)}</p>${spec?`<p>制作材料：${esc(inputsText(spec.inputs))}</p>`:''}${button('economy:build:'+p.id)}</div></article>`;
 }).join('')||'<p>本阶段暂无设备。</p>'}</div></details>`;
 const nodes=b.nodes.filter(n=>n.unlockStage===stage),future=stage>current;
 const modeTabs=`<nav class="study-mode-nav" aria-label="理论与实践"><button type="button" data-study-mode="theory" aria-pressed="${mode==='theory'}">理论学习</button><button type="button" data-study-mode="practice" aria-pressed="${mode==='practice'}">实践</button></nav>`;
 const tabs=modeTabs+`<nav class="study-stage-nav" aria-label="按文明阶段选择科技">${studyStages.map((s,i)=>`<button type="button" data-course-stage="${i}" aria-pressed="${i===stage}"><small>第 ${i+1} 阶段${i>current?' · 预览':i===current?' · 当前':''}</small><strong>${s.name}</strong><span>${s.era}</span></button>`).join('')}</nav>`;
 const overview=`<header class="study-stage-overview"><span class="eyebrow">${curriculum.era} · ${future?'尚未开放':stage<current?'可继续研习':'当前主线'}</span><h3>${curriculum.goal}</h3><p>${curriculum.flow}</p></header>`;
 const planned=`<aside class="study-planned"><strong>后续接入</strong>${curriculum.planned.map(p=>`<p>${p}</p>`).join('')}</aside>`;
 if(mode==='practice'){
  const capabilities=nodes.filter(n=>n.requiresPractice);
  return `${tabs}<header class="study-stage-overview"><span class="eyebrow">${curriculum.era} · 实践</span><h3>把所学变成可用的本领</h3><p>完成理论后点亮实践，再去生产、建设或制作。纯加成课程学完即生效。</p></header><div class="school-toolbar"><strong>已点亮 ${capabilities.filter(n=>n.practiced).length} / ${capabilities.length} 项</strong><span class="subtle">点亮不耗时间与材料；实物仍需自行制作。</span></div><section class="practice-grid" aria-label="科技实践">${capabilities.map(n=>`<article class="practice-card ${n.practiced?'is-active':n.known?'is-ready':''}"><div class="practice-heading"><img src="${courseArtUrl(n.id)}" width="64" height="64" alt=""><div><span class="eyebrow">${COURSE_TRACKS[n.track].name}</span><h3>${esc(n.name)}</h3><small>${n.practiced?'✓ 已点亮':n.known?'理论已完成 · 待实践':'先完成理论学习'}</small></div></div><p>${esc(n.benefit)}</p><p class="subtle">${esc(n.use)}</p><div class="practice-action">${n.practiced?'<span class="learned-stamp">✓ 能力已启用</span>':button('economy:branchpractice:'+n.id)}${!n.known?`<button type="button" class="text-btn" data-study-theory="${n.id}">去学理论 →</button>`:''}</div></article>`).join('')||'<p class="study-preview">本阶段暂无待点亮能力。</p>'}</section>${equipment}`;
 }
 if(future||!nodes.length)return `${tabs}${overview}<div class="study-preview"><h3>${future?'到达该阶段后开放':'资本科技筹备中'}</h3>${curriculum.notes.map(p=>`<p>${p}</p>`).join('')}${planned}</div>`;
 const selected=nodes.find(n=>n.id===selectedId)??nodes.find(n=>!n.known&&g.actions.find(a=>a.id==='economy:branchlearn:'+n.id)?.enabled)??nodes[0];
 const state=(n:typeof selected)=>n.known?'理论已完成':!n.active?'阶段未开放':g.actions.find(a=>a.id==='economy:branchlearn:'+n.id)?.enabled?'可研习':'条件不足';
 const core=nodes.filter(n=>n.track!=='accounting');
 const lanes=Object.entries(COURSE_TRACKS).filter(([id])=>core.some(n=>n.track===id)).map(([id,t])=>({id,name:t.name}));
 const treeNode=(n:typeof selected):TreeNodeSpec=>{const offer=g.actions.find(a=>a.id==='economy:branchlearn:'+n.id),stateClass=n.known?'known':!n.active?'inactive':offer?.enabled?'ready':'locked';
  return {id:n.id,name:n.name,image:courseArtUrl(n.id),lane:n.track,parents:n.parents,selected:n.id===selected.id,stateClass,dataAttr:'data-course',stateText:state(n),sub:stateClass==='ready'?`${offer?.time??0} 天 · 压力 +${offer?.energy??0}`:n.parents.length?'前置 '+branchRequirements(n.parents):'基础知识'};
 };
 const selectedOffer=g.actions.find(a=>a.id==='economy:branchlearn:'+selected.id);
 const applicationLabel=(name:string,ids:string[])=>{const unlock=Math.max(...ids.map(id=>b.nodes.find(n=>n.id===id)?.unlockStage??0));return name+(unlock>stage?'（'+studyStages[unlock].era+'知识齐备后）':'');};
 const applications=[...Object.entries(FARM_PROJECT_TECH).filter(([,tech])=>tech===selected.id).map(([kind])=>FARM_PROJECT_NAMES[kind as keyof typeof FARM_PROJECT_NAMES]+(kind==='paddy'?'（播种用途地改造，需自行开工）':'（其他用途地设施，需自行开工）')),...Object.entries(b.products).filter(([,ids])=>ids.includes(selected.id)).map(([id,ids])=>applicationLabel(productName(id),ids)),...Object.entries(b.processes).filter(([,ids])=>ids.includes(selected.id)).map(([id,ids])=>applicationLabel(g.economy!.processes.find(p=>p.id===id)?.name??id,ids))];
 const detail=`<aside class="course-inspector" tabindex="-1">${storyPanel(g,'learning')}${landscapeBenefits(g,'reading')}<img class="course-skill-art" src="${courseArtUrl(selected.id)}" alt="${esc(selected.name)}示意图" width="144" height="112"><div class="inspector-head"><span>${COURSE_TRACKS[selected.track].name}<small>${state(selected)} · ${SUBJECT_NAMES[selected.subject]}</small></span></div><h3>${esc(selected.name)}</h3><div class="study-purpose"><span class="detail-label">学会后能做什么</span><p>${esc(selected.benefit)}</p><span class="detail-label">在哪里用</span><p>${esc(selected.use)}</p>${applications.length?`<p class="subtle">关联工具与工艺：${[...new Set(applications)].map(esc).join('、')}。还需相应材料与实物条件。</p>`:''}</div><div class="prerequisite-chain"><span class="detail-label">前置知识</span>${selected.parents.length?selected.parents.map(id=>{const n=b.nodes.find(x=>x.id===id)!;return `<button type="button" data-course="${id}" class="prerequisite ${n.known?'met':''}">${n.known?'✓':'○'} ${n.name}${n.unlockStage!==stage?` · 第${n.unlockStage+1}阶段`:''} →</button>`;}).join(''):'<span class="met">✓ 无前置要求</span>'}</div>${!selected.known&&selectedOffer?.reason?`<p class="study-blocker">${esc(selectedOffer.reason)}</p>`:''}${!selected.known?`<p class="study-progress">已研习 ${Math.round(selected.study.done*100)/100} / ${selected.study.total} 工日 · 每次最多投入7天，进度保留</p><progress aria-label="课程研习进度" value="${selected.study.done}" max="${selected.study.total}"></progress>`:''}<div class="inspector-action">${!selected.known?button('economy:branchlearn:'+selected.id):`<div class="learned-stamp">✓ 理论已完成</div>${selected.requiresPractice?`<p class="study-blocker">${selected.practiced?'实践已点亮，能力可用。':'还需到实践页点亮，才能使用。'}</p><button type="button" class="text-btn" data-study-mode="practice">前往实践 →</button>`:'<p class="subtle">纯加成已生效，无需实践。</p>'}${!selected.archived?button('economy:brancharchive:'+selected.id):''}${!selected.heirKnown?button('economy:branchteach:'+selected.id):''}`}</div><details><summary>传承与学习说明</summary><p>${selected.inherited?'前代已学，本人享传承减费。':'个人理论需亲自学习。'}弟子${selected.heirKnown?'已掌握':'未掌握'}。理论与本人实践跨阶段保留，弟子需自己点亮实践。</p></details></aside>`;
 const legacy=nodes.filter(n=>n.track==='accounting');
 return `${tabs}${overview}<div class="school-toolbar"><strong>本阶段理论已完成 ${nodes.filter(n=>n.known).length} / ${nodes.length} 门</strong><span class="subtle">选择节点，查看用途、前置与实际学习条件。</span></div><div class="school-workbench"><section class="course-library"><div class="tree-network" tabindex="0" role="region" aria-label="${curriculum.name}科技树">${treeGraph(core.map(treeNode),lanes,{ariaLabel:curriculum.name+'科技树'})}</div><div class="study-stage-notes">${curriculum.notes.map(p=>`<p>${p}</p>`).join('')}</div>${legacy.length?`<details class="school-collection" ${selected.track==='accounting'?'open':''}><summary>现行阶段结算核算 · ${legacy.length} 门</summary><p>以下课程仍提供原有阶段回报加成，尚未替换为经营能力；不会伪装成市场或资本科技。</p>${legacy.map(n=>`<button type="button" class="text-btn" data-course="${n.id}"><img class="course-list-art" src="${courseArtUrl(n.id)}" alt="" width="36" height="36">${n.known?'✓ ':''}${n.name} →</button>`).join('')}</details>`:''}${planned}${stage>=1?`<details class="school-collection"><summary>已留存的工艺与供货渠道</summary>${(stage>=2?['electric','metal']:['metal']).map(id=>b.channels.includes(id)?`<p>${id==='electric'?'电工材料商':'稳定金属供货'}：已联络</p>`:button('economy:channel:'+id)).join('')}<p>工艺规程：${esc(b.protocols.map(id=>g.economy!.processes.find(p=>p.id===id)?.name??id).join('、')||'暂无')}</p></details>`:''}</section>${detail}</div>`;
}
export function branchCatalog(products=false):string{
 return `<section class="card"><h2>0.27.0 · 文明阶段、社会服务与自选结算</h2><p>科技按农场、工坊、贸易与资本组织；材料、力学等作为知识标签。部分课程随社会发展开放，开放批次由开局选择的发展框架决定。社会服务不靠点树：公地采食、公井、公共磨坊、市政自来水随阶段自动提供。玩家随时可结算当前社会。当前系统包括${SYSTEMS.map(s=>s.name).join('、')}。学习不消耗样品。</p>${BRANCH_PATHS.map(p=>`<p>${p.name}：${branchRequirements(p.nodes)}</p>`).join('')}</section>`+(products?ALL_PRODUCTS.filter(p=>BRANCH_PRODUCTS[p.id]).map(p=>`<section class="card"><h3>${p.name}</h3><p>${p.effect}</p><p>知识：${branchRequirements(BRANCH_PRODUCTS[p.id])}；前置产品验证：${(INDUSTRY_PRODUCTS.find(x=>x.id===p.id)?.parents??[]).map(productName).join(' + ')||'无'}</p><p>材料：${inputsText(p.inputs)}</p></section>`):[...BRANCH_NODES,...ERA_NODES].map(n=>`<section class="card"><h3>${n.id} ${n.name}</h3><p>前置：${branchRequirements(n.parents)}；只依赖前置知识，学习花时间与压力。</p><p>${n.benefit}</p></section>`)).join('');
}
