import {subjectArt,artUrl,illustration} from './illustration.js';
import {uiIcon} from './ui-icons.js';
import {INDUSTRY_PRODUCTS,SYSTEMS} from '../../src/game/model/industry.js';
import {productName} from '../../src/game/systems/industry-products.js';
import type {SessionObservation} from '../../src/runtime/session.js';
import {ERA_NODES,BRANCH_NODES,BRANCH_PATHS,BRANCH_PRODUCTS} from '../../src/game/model/branches.js';
import {ALL_PRODUCTS,SUBJECT_NAMES} from '../../src/game/systems/economy-catalog.js';
import {esc,inputsText} from './economy-view.js';
import {treeGraph,type TreeNodeSpec} from './tree-view.js';
export const branchRequirements=(ids:string[]|undefined)=>ids?.map(id=>[...BRANCH_NODES,...ERA_NODES].find(n=>n.id===id)?.name??id).join(' + ')||'无';
export function branchPage(g:SessionObservation['game'],button:(id:string)=>string,selectedId=''):string{
 const b=g.economy!.branchView!;
 const known=b.nodes.filter(n=>n.known);
 const selected=b.nodes.find(n=>n.id===selectedId)??b.nodes.find(n=>!n.known&&!n.missing.length)??known[0]??b.nodes[0];
 const glyph=(n:typeof selected)=>uiIcon(n.id==='A1'?'drop':n.subject==='agronomy'?'plant':n.subject==='materials'?'layers':n.subject==='mechanics'?'motion':'people');
 const state=(n:typeof selected)=>!n.active?(n.recorded?'历史已学 · 本阶段停用':'其他社会课程'):n.known?'已掌握':n.missing.length?'待前置':'可研习';
 const lanes=[{id:'agronomy',name:SUBJECT_NAMES.agronomy},{id:'materials',name:SUBJECT_NAMES.materials},{id:'mechanics',name:SUBJECT_NAMES.mechanics},{id:'organization',name:SUBJECT_NAMES.organization}];
 const treeNode=(n:typeof selected):TreeNodeSpec=>{const offer=g.actions.find(a=>a.id==='economy:branchlearn:'+n.id),stateClass=!n.active?'inactive':n.known?'known':n.missing.length?'locked':'ready';
  return {id:n.id,name:n.name,image:artUrl(subjectArt(n.subject)),lane:n.subject,parents:n.parents,selected:n.id===selected.id,stateClass,dataAttr:'data-course',
   stateText:stateClass==='inactive'?state(n):stateClass==='known'?'✓ '+state(n):stateClass==='locked'?'⌑ '+state(n):'○ '+state(n),
   sub:stateClass==='locked'?`前置 ${n.missing.length} 项`:stateClass==='ready'?`时间 ${offer?.time??0}　精力 ${offer?.energy??0}`:SUBJECT_NAMES[n.subject]};};
 const detail=`<aside class="course-inspector">${illustration(subjectArt(selected.subject))}<div class="inspector-head"><span class="inspector-symbol">${glyph(selected)}</span><span>${SUBJECT_NAMES[selected.subject]}<small>${state(selected)}</small></span></div><h3>${selected.name}</h3><p>${esc(selected.benefit)}</p>${selected.epigraph?`<blockquote>${esc(selected.epigraph)}</blockquote>`:''}<p>${selected.scope}${!selected.active?' · 本社会不生效；保留历史记录，不授予跨阶段加成':''}</p><div class="prerequisite-chain"><span class="detail-label">前置知识</span>${selected.parents.length?selected.parents.map(id=>{const n=b.nodes.find(x=>x.id===id)!;return `<button type="button" data-course="${id}" class="prerequisite ${n.known?'met':''}">${n.known?'✓':'○'} ${n.name} →</button>`;}).join(''):'<span class="met">✓ 无前置要求</span>'}<span class="chain-arrow">↓</span><strong>${selected.name}</strong></div><div class="inspector-action">${!selected.known?button('economy:branchlearn:'+selected.id):`<div class="learned-stamp">✓ 已掌握</div>${!selected.archived?button('economy:brancharchive:'+selected.id):''}${!selected.heirKnown?button('economy:branchteach:'+selected.id):''}`}</div><details><summary>传承与学习说明</summary><p>${selected.inherited?'前代已学，本人享传承减费。':'学习花费时间与精力，不消耗样品。'}弟子${selected.heirKnown?'已掌握':'未掌握'}。</p></details><button type="button" class="inspector-rules" data-guide="学科">学堂完整规则</button></aside>`;
 return `<div class="school-toolbar"><div class="knowledge-count">${uiIcon('book')}<strong>${known.length}<small> / ${b.nodes.length}</small></strong><span>已学会的课程</span></div><span class="subtle">选择课程，查看用途、前置与学习花费。</span></div><div class="illustrated-categories">${lanes.map(l=>{const group=b.nodes.filter(n=>n.subject===l.id),first=group.find(n=>n.active&&!n.known&&!n.missing.length)??group[0];return first?`<button type="button" class="category-card ${selected.subject===l.id?'selected':''}" data-course="${first.id}">${illustration(subjectArt(l.id),'category-illustration')}<span><strong>${l.name}</strong><small>${group.filter(n=>n.known).length} / ${group.length} 门已掌握</small></span></button>`:'';}).join('')}</div><div class="school-workbench"><section class="course-library"><p class="tree-legend subtle">✓ 已掌握 / ○ 可研习 / ⌑ 待前置 / 灰显 未开放或停用</p><div class="tree-network" tabindex="0" role="region" aria-label="学科树，可横向滚动">${treeGraph(b.nodes.map(treeNode),lanes,{ariaLabel:'学科树'})}</div><details class="school-collection"><summary>学习路线</summary>${b.paths.map(p=>`<article class="family-item"><h3>${p.name}</h3><progress class="tower-progress" aria-label="${p.name}已学会 ${p.learned} / ${p.nodes.length}" value="${p.learned}" max="${p.nodes.length}"></progress><p>${branchRequirements(p.nodes)}</p></article>`).join('')}</details><details class="school-collection"><summary>渠道与家族工艺</summary>${['electric','metal'].map(id=>b.channels.includes(id)?`<p>${id==='electric'?'电工材料商':'稳定金属供货'}：已联络</p>`:button('economy:channel:'+id)).join('')}<p>已试制规程：${esc(b.protocols.map(id=>g.economy!.processes.find(p=>p.id===id)?.name??id).join('、')||'暂无')}</p></details></section>${detail}</div>`;
}
export function branchCatalog(products=false):string{
 return `<section class="card"><h2>0.27.0 · 文明阶段、社会服务与自选结算</h2><p>力学、材料、农学、组织从根节点分叉。部分课程随社会发展开放，开放批次由开局选择的发展框架决定。社会服务不靠点树：公地采食、公井、公共磨坊、市政自来水随阶段自动提供。玩家随时可结算当前社会。当前系统包括${SYSTEMS.map(s=>s.name).join('、')}。学习不消耗样品。</p>${BRANCH_PATHS.map(p=>`<p>${p.name}：${branchRequirements(p.nodes)}</p>`).join('')}</section>`+(products?ALL_PRODUCTS.filter(p=>BRANCH_PRODUCTS[p.id]).map(p=>`<section class="card"><h3>${p.name}</h3><p>${p.effect}</p><p>知识：${branchRequirements(BRANCH_PRODUCTS[p.id])}；前置产品验证：${(INDUSTRY_PRODUCTS.find(x=>x.id===p.id)?.parents??[]).map(productName).join(' + ')||'无'}</p><p>材料：${inputsText(p.inputs)}</p></section>`):[...BRANCH_NODES,...ERA_NODES].map(n=>`<section class="card"><h3>${n.id} ${n.name}</h3><p>前置：${branchRequirements(n.parents)}；只依赖前置知识，学习花时间与精力。</p><p>${n.benefit}</p></section>`)).join('');
}
