import { ALL_TOPICS as TOPICS, SUBJECT_NAMES, ALL_PRODUCTS as PRODUCTS, PLANNED_PRODUCTS, ALL_GOODS as GOODS, ALL_PROCESSES as PROCESSES, CROPS } from '../../src/game/systems/economy-catalog.js';
import { SUBJECTS } from '../../src/game/model/economy.js';
import type { Subject } from '../../src/game/model/economy.js';
export const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function inputsText(inputs:Record<string,number>):string{return Object.entries(inputs).map(([id,n])=>`${n} ${GOODS[id]?.name??id}`).join(' + ');}
export function needsText(needs:Partial<Record<Subject,number>>):string{return Object.entries(needs).map(([id,n])=>`${SUBJECT_NAMES[id as Subject]} ${n}阶`).join('、');}
export function disciplineCatalog():string{return `<section class="card"><h2>学科主干</h2><p>各学科独立进阶；子分支后续开发。首阶可直接学习，后续先取得对应实验、实践证据或家族／地区记录，再学习。原料、产品和跨学科生产条件只放在产品详情。</p></section>${SUBJECTS.map(subject=>`<section class="card"><h2>${SUBJECT_NAMES[subject]}</h2><div class="flow">${TOPICS.filter(t=>t.subject===subject).map(t=>`<span>${t.level} · ${t.name}</span>`).join('<b>→</b>')}</div></section>`).join('')}`;}
export function productCatalog():string{return `<section class="card"><h2>产品与效果</h2><p>${PRODUCTS.length}项设备已接入。按用途选择，再展开生产条件；不显示跨学科连线，不做工具／消耗品分类。实际制造只检查详情要求，不要求先造前一产品。</p></section>${[...new Set(PRODUCTS.map(p=>p.category))].map(category=>`<section class="card"><h2>${category}</h2>${PRODUCTS.filter(p=>p.category===category).map(p=>`<details><summary>${p.id} ${p.name} · ${p.id==='U02'?'每季一次本人播种节省个人投入，仍扣种子与耐用度':p.effect}</summary><p>效果来源：${p.from.map(id=>PRODUCTS.find(p=>p.id===id)?.name??id).join('、')||'独立能力入口'}。这是能力关系，不是制造前置。</p><p>学科：${needsText(p.requires)}</p><p>投入：${inputsText(p.inputs)}；制造安装的时间与精力以行动报价为准。初始耐用度见现行规则，储存设施不按季磨损。</p></details>`).join('')}</section>`).join('')}<section class="card"><h2>作物与加工</h2>${Object.values(CROPS).map(c=>`<p>${c.name}：${c.duration}季生长，基础收成${c.yield}；另留种1份、秸秆${c.straw}。天气、肥力、设备和收获延迟影响实际产量。</p>`).join('')}${PROCESSES.map(p=>`<details><summary>${p.name} → ${inputsText(p.outputs)}</summary><p>${inputsText(p.inputs)}；${needsText(p.requires)}${p.equipment?'；设备：'+PRODUCTS.find(x=>x.id===p.equipment)?.name:''}；${p.wait?'跨季完成':'即时完成'}。</p></details>`).join('')}</section><details class="card"><summary>待接入产品（${PLANNED_PRODUCTS.length}项，不可制造）</summary>${PLANNED_PRODUCTS.map(([id,name,effect])=>`<p>${id} ${name}：${effect}</p>`).join('')}<p>电磁、通信与现代制造已接入当前现代版本；医疗等仍未实现。</p></details>`;}
export function economyRulesPage():string{return `<section class="card"><h2>从第一季开始</h2><p>四季一年，每季12时间；体力劳动通常4时间/4精力，学习4/2，管理2/1，天赋可减免。休息用4时间恢复5精力，疗养用4时间、1精力、2钱恢复8健康；实际报价以行动按钮为准。界面显示即食口粮与实物食品总量；季末先结算工作和田间生长，再吃粮和计算保存损耗。</p></section><section class="card"><h2>长期经营与新的能力</h2><p>生产组织1阶可签长期供粮协议，按需配送至4份储备；2阶可由熟练农工托管完整种植循环、工匠执行生产计划，并开启补货、自动交付和维护。真实资源、工资和设备仍结算，日常操作逐步交出去。</p><p>生活与工资优先，自动补货计入在途库存并保留现金底线；设备低耐用时自动送修，避免在制工序。家族契约让全部安排跨代自动接续；没有契约也只需一次接续行动，不用重配。</p><p>稳定供粮、地区机械供应、深层排水采矿、蒸汽供能接入依次引入生活保障、合作交付、矿料开拓、无水动力与窑炉加速。供粮与机械供应可以独立发展；采矿要求机械供应，蒸汽要求采矿。项目需要真实运行验证，付钱不等于完成。</p></section><section class="card"><h2>地区商城</h2><p>清单可选择多种物资、设备、教材和家庭资产，整单结账消耗时间与精力。现货即刻到货，外地订货次季开始交付；每季运输容量和库存有限。购买不增加制造知识或地区生产进度。面粉与小麦同为1份生活，采购价2、交付价1。</p><p>已有设备可付费维修：本季停机，次季恢复；在制设备须先完工。委托培训让雇员停工一季，下季提升经验。教材是永久学习来源，授课只教本人下一课题。粮仓提高保护容量，书室让记录同时教导后辈下一课题。已付款订单与资产跨代保留。</p></section><section class="card"><h2>学科与生产</h2><p>选择学科主干，首阶直接学习；之后通过固定课题实验、真实制作或家族记录继续学习。商品是否可造，由其详情中的学科、原料和设备条件决定。每项实验只给对应课题证据，不能无限刷通用研究点。</p><p>设备制造后立即安装。泵按季自动灌溉；工具在相应工序生效。水轮每季提供一次省力加工，但仍须选择加工配方并支付原料。不能把同一材料重复算为自动生产和雇工生产。</p></section><section class="card"><h2>种植与加工</h2><p>家庭共用一块田：播种、缺水管理、成熟后收获。小麦与大豆可支付生活，亚麻进入纤维与绳索；种子不能当食物。收获留下种子和秸秆，大豆恢复肥力；作物成熟后拖延会损失收成。加工与保存设施提供新的出口。</p></section><section class="card"><h2>雇佣与组织成长</h2><p>生产组织1阶可招普通雇工，2阶可招农工和工匠，3阶扩大容量并通过家族合同记录支持换代接续，4阶可培训，5阶可招生产负责人，6阶允许负责人交付工业余货并分成。首次需花行动招募并安排任务，之后季末自动尝试工作。</p><p>工资在实际工作前扣除；缺钱、缺料、设备占用或等待生长时待命，不收费。招募费不退还。普通雇工起初不能播种，熟练农工会种植；工匠会专业配方但需要实际设备。人员经验8后能够执行更多任务或按双份原料加工，工资相应增加。雇工经验不转给本人。</p></section><section class="card"><h2>跨代与地区变化</h2><p>记录、设备、存货、田地、员工经验和在制品保留，个人学科理解需教学。家族保存生产组织3阶记录后合同自动接续，否则交接时暂停，需本人恢复。实际冶铁或纤维生产达到3批且传播相关知识后，地区供给形成，对应采购降价但不能买卖套利。</p><p>所有环境统一从农学1阶、一块田、基础钱粮和种子起步，没有工业设备或高阶知识。六科各10阶，现代工业需要逐步建设。副本独立选择，投入物资与真实生产证明后首次完成发放材料、教材及供应渠道。教材仍需逐阶学习。后辈18岁成年后可安排季末交接，不再固定16季换代。初代40岁、后辈16岁；30岁且没有子嗣的人物迎来零岁后辈。健康耗尽或自然衰老会死亡；没有成年继任者则结束。知识和副本完成不强制结束游戏。</p></section>`;}
