import { ALL_TOPICS as TOPICS, SUBJECT_NAMES, ALL_PRODUCTS as PRODUCTS, PLANNED_PRODUCTS, ALL_GOODS as GOODS, ALL_PROCESSES as PROCESSES, CROPS } from '../../src/game/systems/economy-catalog.js';
import { SUBJECTS } from '../../src/game/model/economy.js';
import type { Subject } from '../../src/game/model/economy.js';
export const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function inputsText(inputs:Record<string,number>):string{return Object.entries(inputs).map(([id,n])=>`${n} ${GOODS[id]?.name??id}`).join(' + ');}
export function needsText(needs:Partial<Record<Subject,number>>):string{return Object.entries(needs).map(([id,n])=>`${SUBJECT_NAMES[id as Subject]} ${n}阶`).join('、');}
export function disciplineCatalog():string{return `<section class="card"><h2>学科主干</h2><p>各学科独立进阶；子分支后续开发。首阶可直接学习，后续先取得对应实验、实践证据或家族／地区记录，再学习。原料、产品和跨学科生产条件只放在产品详情。</p></section>${SUBJECTS.map(subject=>`<section class="card"><h2>${SUBJECT_NAMES[subject]}</h2><div class="flow">${TOPICS.filter(t=>t.subject===subject).map(t=>`<span>${t.level} · ${t.name}</span>`).join('<b>→</b>')}</div></section>`).join('')}`;}
export function productCatalog():string{return `<section class="card"><h2>产品与效果</h2><p>${PRODUCTS.length}项设备已接入。按用途选择，再展开生产条件；不显示跨学科连线，不做工具／消耗品分类。实际制造只检查详情要求，不要求先造前一产品。</p></section>${[...new Set(PRODUCTS.map(p=>p.category))].map(category=>`<section class="card"><h2>${category}</h2>${PRODUCTS.filter(p=>p.category===category).map(p=>`<details><summary>${p.id} ${p.name} · ${p.id==='U02'?'每季一次本人播种节省个人投入，仍扣种子与耐用度':p.effect}</summary><p>效果来源：${p.from.map(id=>PRODUCTS.find(p=>p.id===id)?.name??id).join('、')||'独立能力入口'}。这是能力关系，不是制造前置。</p><p>学科：${needsText(p.requires)}</p><p>投入：${inputsText(p.inputs)}；制造安装的时间与压力以行动报价为准。初始耐用度见现行规则，储存设施不按季磨损。</p></details>`).join('')}</section>`).join('')}<section class="card"><h2>作物与加工</h2>${Object.values(CROPS).map(c=>`<p>${c.name}：${c.duration}天生长，基础收成${c.yield}；另留种1份、秸秆${c.straw}。天气、肥力、设备和收获延迟影响实际产量。</p>`).join('')}${PROCESSES.map(p=>`<details><summary>${p.name} → ${inputsText(p.outputs)}</summary><p>${inputsText(p.inputs)}；${needsText(p.requires)}${p.equipment?'；设备：'+PRODUCTS.find(x=>x.id===p.equipment)?.name:''}；${p.wait?'跨季完成':'即时完成'}。</p></details>`).join('')}</section><details class="card"><summary>待接入产品（${PLANNED_PRODUCTS.length}项，不可制造）</summary>${PLANNED_PRODUCTS.map(([id,name,effect])=>`<p>${id} ${name}：${effect}</p>`).join('')}<p>电磁、通信与现代制造已接入当前现代版本；医疗等仍未实现。</p></details>`;}
export function economyRulesPage():string{return `<section class="card"><h2>日历连续向前</h2><p>行动以天或半天计时，可以跨越自然季节。作物按播种批次的固定节气成熟，饮食、压力缓解和储粮损耗随经过时间结算；换季不清空补水，也不额外降低压力。具体投入以行动按钮为准。</p><p>等待可选择半天、7天或等到某块田成熟。遇到计划到期、成熟、缺粮、节气或节日会停下；学习和地块工程保留累计进度。</p></section><section class="card"><h2>种植与生活</h2><p>探索未知格子，开垦新田，发现种子；根据播种季安排作物。补水在干燥天气消退较快，晴和时较慢，连雨时不消退。渠与护田林持续帮助相邻地块。成熟后手动收获，不会自动复种。</p><p>每天有食材和柴火就做饭，否则使用干粮。主动烹饪当次享用，提供短期调养。种子不会被食用。粮仓保护一定容量，超出部分按存放时间逐渐损耗。</p></section><section class="card"><h2>生产、运输与补货</h2><p>这些后续模块暂按独立90天经营周期兼容运行，与自然四季无关。市场显示下次补货日期，待交付订单显示预计完成日期；维修、培训与设备运行次数暂沿用该周期。</p><p>采购不耗时间和压力，仍受钱财、库存、运输和预算约束。现货立即交付，订货按展示日期交付。本人承担的系统劳动需要真实时间和压力，雇工实际工作才支付工资。</p></section><section class="card"><h2>阶段与传承</h2><p>文明阶段按剩余天数倒计时。提前结束立即兑现已取得回报，剩余天数按50%折算、向下取整到半天加入下一阶段，不额外等待换季。未经历的时间不产生预估收益。</p><p>弟子成年后可以准备交接，不需要等季末。日期、阶段期限、地块、库存与在制进度继续保留；个人修为和知识不会自动复制。</p></section>`;}
