import type { SessionObservation } from '../../src/runtime/session.js';
import { esc,inputsText,needsText } from './economy-view.js';
import { ALL_PRODUCTS as PRODUCTS,CROPS } from '../../src/game/systems/economy-catalog.js';
export function operationsPage(g:SessionObservation['game'],button:(id:string)=>string):string{
 const e=g.economy!,o=e.operationsView;if(!o)return '';
 const panel=(title:string,body:string)=>`<section class="panel"><div class="panel-head"><h2>${title}</h2></div><div class="panel-body">${body}</div></section>`;
 const a=(op:string,t:string)=>button('economy:'+op+':'+t);
 const summary=panel('家业总览 · '+o.stage,`${e.expeditionView?`<p>从农业逐步建设文明，家业用于稳定粮食、加工与物流。副本按自身能力进入，实际投入换取高阶材料、教材和供应；完成后仍可继续发展。</p><button data-page="副本">查看副本 →</button>`:e.towerView?`<p>文明试炼已完成 ${e.towerView.floor}/${e.towerView.total} 层。家业用于保障工程供应；地区项目开放生产能力，知识数量不再是通关条件。</p><button data-page="试炼">查看宏大工程 →</button>`:e.branchView?'<p>三路线试点按需要学习，没有地区项目或集齐知识胜利条件。已完成的工艺规程与经营安排可跨代保留；后辈的个人知识独立。</p>':`<p>知识 ${g.victory?.mastered.length}/${g.victory?.required}，实际成果 ${o.completed.length}/${o.parameters.requiredAchievements}。两者都达成并通过季末生存结算才获胜。</p>`}${o.paused?'<p>换代后的经营安排已保存，等待接续。</p>'+a('resumeplans','family'):''}<div class="family-grid"><article class="family-item"><h3>生活保障</h3><p>${o.food?'供粮协议运行中；本季预留'+o.foodReserved+'粮':'尚未签订供粮协议'}；每季按需补足至${o.foodTarget}份储备。</p><p>本季基本粮款还需${o.food?Math.max(0,g.parameters.foodPerTurn-e.foodTotal)*g.parameters.foodPrice:0}钱；补到协议目标预计${o.food?Math.max(0,o.foodTarget-e.foodTotal)*g.parameters.foodPrice:0}钱。签约不免除粮款。</p><p>田地：${o.farm?(o.farm==='rotation'?'小麦大豆轮作':CROPS[o.farm].name)+'托管':'亲自经营'}。</p></article><article class="family-item"><h3>持续生产</h3><p>${o.production?o.recipes.find(p=>p.id===o.production!.recipe)?.name+' · '+(o.production.mode==='sell'?'持续生产':'备货后待命')+(e.workers.artisan?.active?'':'（已暂停）'):'尚未建立生产计划'}。</p><p>补货${o.supplies?'开启':'暂停'} · 自动交付${o.sales?'开启':'暂停'} · 维护${o.maintenance?'开启':'暂停'}。</p></article></div>${o.notice.length?`<h3>上季需关注</h3><ul>${o.notice.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:'<p>上季没有经营告警。未启用的委托可在下方管理安排。</p>'}`);
 const projects=panel('新能力与地区项目',`<p>项目由真实学科与设备能力开放。启动支付材料与组织费用，此后靠实际运行验证，不需要每季点击项目按钮。未投入的项目可先查看条件。</p>${o.projectsCatalog.map(p=>`<details ${o.activeProject===p.id?'open':''}><summary>${p.name} · ${p.state==='complete'?'已达成':o.activeProject===p.id?'运行验证 '+p.progress+'/'+o.parameters.commissionSeasons:p.blockers.length?'尚缺条件':'可以开展'}</summary><p>${p.effect}</p><p>条件：${needsText(p.needs)}${p.previous?'；需先完成前一地区项目':''}。<br>启动投入：${inputsText(p.inputs)||'无材料'}；组织费${o.parameters.projectFee}钱。<br>验证：${p.test}；共${o.parameters.commissionSeasons}个有效季，生活保障要求连续达标。</p>${p.blockers.length?'<p>'+esc(p.blockers.join('；'))+'</p>':''}${p.state!=='complete'?a('projectstart',p.id):''}${o.activeProject===p.id?a('projectpause','current'):''}</details>`).join('')}`);
 const management=panel('管理既有事务',`<details><summary>供粮协议 · ${o.food?'已开启':'未开启'}</summary><p>按需付费、每季自动配送，先预留市场口粮；不占个人行动和普通采购运输。仍需稳定收入支付粮款。</p>${a('foodplan',o.food?'off':'on')}</details><details><summary>农业托管 · ${o.farm?'已安排':'未安排'}</summary><p>需熟练农工和生产工序知识。统一播种、管理、收获、留种，有堆肥时改善低肥力；雇员按实际工作季领工资。若需购种或补肥，可开启自动补货。</p>${['wheat','soy','flax','rotation','off'].map(t=>a('farmplan',t)).join('')}</details><details><summary>生产计划 · ${o.production?'已安排':'未安排'}</summary><p>需熟练工匠。备货模式达到目标后待命；持续生产可配合自动交付。跨季工序由雇员自动接续，每季不需重复点制作。</p>${o.recipes.filter(p=>!p.equipment||e.equipment[p.equipment]!==undefined).map(p=>`<details><summary>${p.name}</summary>${a('productionplan',p.id+'-stock')}${a('productionplan',p.id+'-sell')}</details>`).join('')}${a('productionplan','off')}</details><details><summary>供货、交付与维护</summary><p>自动补货计入已订货物，只补当前计划需要的原料；保留生活、工资与${o.parameters.cashReserve}钱底线。维护期间设备停用，次季自动恢复，正在加工的设备不送修。</p>${a('supplyplan',o.supplies?'off':'on')}${a('salesplan',o.sales?'off':'on')}${a('careplan',o.maintenance?'off':'on')}</details><details><summary>家族契约 · ${o.charter?'自动接续':'换代需一次接续'}</summary>${a('charter','family')}</details>${o.completed.includes('mine')?`<details><summary>矿场合作</summary>${a('mineplan',o.mine?'off':'on')}</details>`:''}${o.completed.includes('steam')?`<details><summary>蒸汽供能</summary>${a('steamplan',o.steam?'off':'on')}</details>`:''}`);
 const staff=panel('运行条件',e.staff.map(w=>`<p>${esc(w.name)}：${w.active?'执行'+esc(w.jobName):'暂停'}，工资${w.wage}钱／工作季；${esc(w.blockers.join('；')||'具备当前工作条件')}</p>`).join('')+`<p>已有设备：${Object.entries(e.equipment).map(([id,n])=>`${PRODUCTS.find(p=>p.id===id)?.name??id} ${n}耐用`).join('、')||'暂无'}。招募、培训及手动操作仍在对应栏目。</p>`);
 return summary+(e.branchView?'':projects)+management+staff;
}
